name: Build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Cette étape force le téléchargement du SDK NumWorks
      - name: Download EADK
        run: git clone https://github.com/numworks/eadk.git eadk

      - name: Install toolchain
        uses: numworks/setup-arm-toolchain@latest
        
      - name: Run make build
        run: make build

      - name: Upload nwa artifact
        uses: actions/upload-artifact@v4
        with:
          name: block-blast-nwa
          path: output/app.nwa

      - name: Run make check
        run: make check
