name: Build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. On télécharge ton code (ton main.c, etc.)
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. On télécharge l'EADK proprement dans le dossier "eadk"
      - name: Checkout EADK
        uses: actions/checkout@v3
        with:
          repository: numworks/eadk
          path: eadk

      # 3. On installe le compilateur
      - name: Install toolchain
        uses: numworks/setup-arm-toolchain@latest
        
      # 4. On lance la compilation
      - name: Run make build
        run: make build

      # 5. On sauvegarde le jeu généré
      - name: Upload nwa artifact
        uses: actions/upload-artifact@v4
        with:
          name: demineur-nwa
          path: output/app.nwa

      # 6. On lance les vérifications
      - name: Run make check
        run: make check
