name: Build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: numworks/setup-arm-toolchain@latest
      - name: Run make build
        run: make build

      - name: Upload nwa artifact
        uses: actions/upload-artifact@v4
        with:
          name: block-blast-nwa
          path: output/app.nwa

      - name: Run make check
        run: make check
